### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by ricleal** [ornl-ndav/django-remote-submission#1]
# TODOs

- [x] 1. Remote file list (given a folder) and transfer (given a file name). 

- [x] 2. Results table:
  - When a task is executed, it would be nice to have some sort of parameter like this:

 ```python
store_results = None # Don't store results
store_results = ['*.txt'] # Store as results all *.txt files
store_results = ['filename1', 'filename2'] # Store as results files ( a result entry per file)
﻿⁠⁠⁠⁠store_results = ["*", "!*.nxs"]﻿⁠⁠⁠⁠ # All files except *.nxs
```

- [x] 3. Examples with the password caching using something default in Django. Ideas:
 - `SESSION_ENGINE = "django.contrib.sessions.backends.cache"﻿⁠⁠⁠⁠`. It uses memory sessions (rather than the DB) for all sessions. The problem is when the memory runs out the sessions disappear..... The server would eventually purge the cache and make the user put on their passwords again...

https://docs.djangoproject.com/en/1.10/topics/http/sessions/#using-cached-sessions

> Session data will be stored directly in your cache. However, session data may not be persistent: cached data can be evicted if the cache fills up or if the cache server is restarted.

- [x] 4. `Log` model needs a flag to tag the log either as `stdout` or `stderr`.

- [x] 5.  Choose the interpreter in `﻿⁠⁠⁠⁠submit_task`﻿⁠. E.g. a parameter ﻿like `⁠⁠⁠⁠interpreter='/usr/bin/python3﻿`⁠⁠ or  `⁠⁠⁠⁠interpreter='/usr/bin/bash`⁠⁠.

- [ ] 6. Minimize dependencies (Let's keep just celery and redis for now).

- [x] 7. `submit_task` needs a `timeout`. We have to see how to kill the process remotely and interrupt the celery task...

- [ ] 8. Ideas (not urgent!):
- Using `django-channels` to have a real update of the tasks. See example: https://github.com/VincentTide/django-channels-celery-example
- Use `django-celery-results` to see in the admin the celery results tables.

**Comment by ricleal** [comment]
* Done:
5, 7, 4, 3
* Tanner is doing:
1,2
* Ricardo is doing:

**Notes:**
3. The first ssh connection deploys the public key in the `authorized_keys` files. No need to store the password.

**TODO**
- `interpreter` is available in `server` and `job` must use one of those. Need to create a constraint... `pre_save` signal?
- `tasks.py` needs refactoring...

Test pass:
`python runtests.py tests.test_tasks.SubmitJobTaskTest.test_program_log_total`
Same test fails :(
`python runtests.py tests.test_tasks.SubmitJobTaskTest`

**Comment by ricleal** [comment]
TODO

```python
import os
import paramiko

from getpass import getpass

'''
Logs in the remote machine adds the client public key to the
authorised keys in the remote host

Set password = getpass() 
For the first login if authorised keys does not exist yet in the remote machine
'''

remote_host = "lealpc.ornl.gov"
#username = os.getlogin()
username = os.environ['USER']
password = None # getpass()
public_key_filename=os.path.expanduser('~/.ssh/id_rsa.pub')


def start(server, username, password=None,  key_filename=None):
	'''
	starts the client
	If password=None uses the key_filename
	'''
    try :
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        if password:
            client.connect(server, port=22, username=username, password=password)
        else:
            client.connect(server, port=22, username=username, key_filename=key_filename) # no passwd needed
    except Exception as e:
        raise RuntimeError(e)
    return client

def deploy_key_if_it_doesnt_exist(client, key_filename):
    '''

    '''
    key = open(key_filename).read()
    client.exec_command('mkdir -p ~/.ssh/')

    command = '''
    KEY="%s"
    if [ -z "$(grep \"$KEY\" ~/.ssh/authorized_keys )" ];
    then 
        echo $KEY >> ~/.ssh/authorized_keys;
        echo key added.;
    fi;
    '''%key

    stdin, stdout, stderr  = client.exec_command(command)

    print(stdout.readlines())
    print(stderr.readlines())

    client.exec_command('chmod 644 ~/.ssh/authorized_keys')
    client.exec_command('chmod 700 ~/.ssh/')


client = start(remote_host, username, password,  key_filename=public_key_filename)

deploy_key_if_it_doesnt_exist(client, key_filename=public_key_filename)


while client:
    key = True
    cmd = input("Command to run: > ")
    if cmd == "":
        break
    chan = client.get_transport().open_session()
    print("** running '%s'" % cmd)
    chan.exec_command(cmd)
    while key:
        if chan.recv_ready():
            print("** recv:\n%s" % chan.recv(4096).decode('ascii'))
        if chan.recv_stderr_ready():
            print("** error:\n%s" % chan.recv_stderr(4096).decode('ascii'))
        if chan.exit_status_ready():
            print("** exit status: %s" % chan.recv_exit_status())
            key = False
            client.close()
client.close()

```
